vim.keymap.set("n", "<C-h>", "<cmd>TmuxNavigateLeft<cr>", {silent = true, noremap = true})
vim.keymap.set("n", "<C-j>", "<cmd>TmuxNavigateDown<cr>", {silent = true, noremap = true})
vim.keymap.set("n", "<C-k>", "<cmd>TmuxNavigateUp<cr>", {silent = true, noremap = true})
vim.keymap.set("n", "<C-l>", "<cmd>TmuxNavigateRight<cr>", {silent = true, noremap = true})
vim.keymap.set("n", "<C-\\>", "<cmd>TmuxNavigatePrevious<cr>", {silent = true, noremap = true})
